/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminErrorsRouteImport } from './routes/admin/errors'
import { Route as AdminOperationsRouteImport } from './routes/admin/operations'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminWorkersRouteImport } from './routes/admin/workers'
import { Route as AuthErrorRouteImport } from './routes/auth.error'
import { Route as BillingIndexRouteImport } from './routes/billing.index'
import { Route as BillingCanceledRouteImport } from './routes/billing.canceled'
import { Route as BillingSuccessRouteImport } from './routes/billing.success'
import { Route as ChannelsIndexRouteImport } from './routes/channels.index'
import { Route as ChannelsIdRouteImport } from './routes/channels.$id'
import { Route as RecordingsIndexRouteImport } from './routes/recordings.index'
import { Route as RecordingsIdRouteImport } from './routes/recordings.$id'
import { Route as RecordingsActiveRouteImport } from './routes/recordings.active'
import { Route as RecordingsFailedRouteImport } from './routes/recordings.failed'
import { Route as RecordingsProcessingRouteImport } from './routes/recordings.processing'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as VerifyEmailIndexRouteImport } from './routes/verify-email.index'
import { Route as VerifyEmailSuccessRouteImport } from './routes/verify-email.success'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs.index'
import { Route as AdminJobsIdRouteImport } from './routes/admin/jobs.$id'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users.index'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminErrorsRoute = AdminErrorsRouteImport.update({
  id: '/admin/errors',
  path: '/admin/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/admin/operations',
  path: '/admin/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkersRoute = AdminWorkersRouteImport.update({
  id: '/admin/workers',
  path: '/admin/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BillingRoute,
} as any)
const BillingCanceledRoute = BillingCanceledRouteImport.update({
  id: '/canceled',
  path: '/canceled',
  getParentRoute: () => BillingRoute,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BillingRoute,
} as any)
const ChannelsIndexRoute = ChannelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChannelsRoute,
} as any)
const ChannelsIdRoute = ChannelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChannelsRoute,
} as any)
const RecordingsIndexRoute = RecordingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecordingsRoute,
} as any)
const RecordingsIdRoute = RecordingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecordingsRoute,
} as any)
const RecordingsActiveRoute = RecordingsActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => RecordingsRoute,
} as any)
const RecordingsFailedRoute = RecordingsFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => RecordingsRoute,
} as any)
const RecordingsProcessingRoute = RecordingsProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => RecordingsRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const VerifyEmailIndexRoute = VerifyEmailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VerifyEmailRoute,
} as any)
const VerifyEmailSuccessRoute = VerifyEmailSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => VerifyEmailRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminJobsRoute,
} as any)
const AdminJobsIdRoute = AdminJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminJobsRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/billing': typeof BillingRouteWithChildren
  '/channels': typeof ChannelsRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recordings': typeof RecordingsRouteWithChildren
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/usage': typeof UsageRoute
  '/verify-email': typeof VerifyEmailRouteWithChildren
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/system': typeof AdminSystemRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/auth/error': typeof AuthErrorRoute
  '/billing/canceled': typeof BillingCanceledRoute
  '/billing/success': typeof BillingSuccessRoute
  '/channels/$id': typeof ChannelsIdRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/recordings/active': typeof RecordingsActiveRoute
  '/recordings/failed': typeof RecordingsFailedRoute
  '/recordings/processing': typeof RecordingsProcessingRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/verify-email/success': typeof VerifyEmailSuccessRoute
  '/billing/': typeof BillingIndexRoute
  '/channels/': typeof ChannelsIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/usage': typeof UsageRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/auth/error': typeof AuthErrorRoute
  '/billing/canceled': typeof BillingCanceledRoute
  '/billing/success': typeof BillingSuccessRoute
  '/channels/$id': typeof ChannelsIdRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/recordings/active': typeof RecordingsActiveRoute
  '/recordings/failed': typeof RecordingsFailedRoute
  '/recordings/processing': typeof RecordingsProcessingRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/verify-email/success': typeof VerifyEmailSuccessRoute
  '/billing': typeof BillingIndexRoute
  '/channels': typeof ChannelsIndexRoute
  '/recordings': typeof RecordingsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/verify-email': typeof VerifyEmailIndexRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/billing': typeof BillingRouteWithChildren
  '/channels': typeof ChannelsRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recordings': typeof RecordingsRouteWithChildren
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/usage': typeof UsageRoute
  '/verify-email': typeof VerifyEmailRouteWithChildren
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/system': typeof AdminSystemRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/auth/error': typeof AuthErrorRoute
  '/billing/canceled': typeof BillingCanceledRoute
  '/billing/success': typeof BillingSuccessRoute
  '/channels/$id': typeof ChannelsIdRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/recordings/active': typeof RecordingsActiveRoute
  '/recordings/failed': typeof RecordingsFailedRoute
  '/recordings/processing': typeof RecordingsProcessingRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/verify-email/success': typeof VerifyEmailSuccessRoute
  '/billing/': typeof BillingIndexRoute
  '/channels/': typeof ChannelsIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceptable-use'
    | '/billing'
    | '/channels'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/notifications'
    | '/onboarding'
    | '/overview'
    | '/pricing'
    | '/privacy'
    | '/recordings'
    | '/refund'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/status'
    | '/terms'
    | '/usage'
    | '/verify-email'
    | '/admin/errors'
    | '/admin/operations'
    | '/admin/jobs'
    | '/admin/users'
    | '/admin/system'
    | '/admin/workers'
    | '/auth/error'
    | '/billing/canceled'
    | '/billing/success'
    | '/channels/$id'
    | '/recordings/$id'
    | '/recordings/active'
    | '/recordings/failed'
    | '/recordings/processing'
    | '/settings/account'
    | '/settings/notifications'
    | '/settings/security'
    | '/verify-email/success'
    | '/billing/'
    | '/channels/'
    | '/recordings/'
    | '/settings/'
    | '/verify-email/'
    | '/admin/jobs/$id'
    | '/admin/jobs/'
    | '/admin/users/$id'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceptable-use'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/notifications'
    | '/onboarding'
    | '/overview'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/status'
    | '/terms'
    | '/usage'
    | '/admin/errors'
    | '/admin/operations'
    | '/admin/system'
    | '/admin/workers'
    | '/auth/error'
    | '/billing/canceled'
    | '/billing/success'
    | '/channels/$id'
    | '/recordings/$id'
    | '/recordings/active'
    | '/recordings/failed'
    | '/recordings/processing'
    | '/settings/account'
    | '/settings/notifications'
    | '/settings/security'
    | '/verify-email/success'
    | '/billing'
    | '/channels'
    | '/recordings'
    | '/settings'
    | '/verify-email'
    | '/admin/jobs/$id'
    | '/admin/jobs'
    | '/admin/users/$id'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/acceptable-use'
    | '/billing'
    | '/channels'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/notifications'
    | '/onboarding'
    | '/overview'
    | '/pricing'
    | '/privacy'
    | '/recordings'
    | '/refund'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/status'
    | '/terms'
    | '/usage'
    | '/verify-email'
    | '/admin/errors'
    | '/admin/operations'
    | '/admin/jobs'
    | '/admin/users'
    | '/admin/system'
    | '/admin/workers'
    | '/auth/error'
    | '/billing/canceled'
    | '/billing/success'
    | '/channels/$id'
    | '/recordings/$id'
    | '/recordings/active'
    | '/recordings/failed'
    | '/recordings/processing'
    | '/settings/account'
    | '/settings/notifications'
    | '/settings/security'
    | '/verify-email/success'
    | '/billing/'
    | '/channels/'
    | '/recordings/'
    | '/settings/'
    | '/verify-email/'
    | '/admin/jobs/$id'
    | '/admin/jobs/'
    | '/admin/users/$id'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  BillingRoute: typeof BillingRouteWithChildren
  ChannelsRoute: typeof ChannelsRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OverviewRoute: typeof OverviewRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecordingsRoute: typeof RecordingsRouteWithChildren
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  UsageRoute: typeof UsageRoute
  VerifyEmailRoute: typeof VerifyEmailRouteWithChildren
  AdminErrorsRoute: typeof AdminErrorsRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminJobsRoute: typeof AdminJobsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminSystemRoute: typeof AdminSystemRoute
  AdminWorkersRoute: typeof AdminWorkersRoute
  AuthErrorRoute: typeof AuthErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/errors': {
      id: '/admin/errors'
      path: '/admin/errors'
      fullPath: '/admin/errors'
      preLoaderRoute: typeof AdminErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workers': {
      id: '/admin/workers'
      path: '/admin/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AdminWorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/canceled': {
      id: '/billing/canceled'
      path: '/canceled'
      fullPath: '/billing/canceled'
      preLoaderRoute: typeof BillingCanceledRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof BillingRoute
    }
    '/channels/': {
      id: '/channels/'
      path: '/'
      fullPath: '/channels/'
      preLoaderRoute: typeof ChannelsIndexRouteImport
      parentRoute: typeof ChannelsRoute
    }
    '/channels/$id': {
      id: '/channels/$id'
      path: '/$id'
      fullPath: '/channels/$id'
      preLoaderRoute: typeof ChannelsIdRouteImport
      parentRoute: typeof ChannelsRoute
    }
    '/recordings/': {
      id: '/recordings/'
      path: '/'
      fullPath: '/recordings/'
      preLoaderRoute: typeof RecordingsIndexRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/recordings/$id': {
      id: '/recordings/$id'
      path: '/$id'
      fullPath: '/recordings/$id'
      preLoaderRoute: typeof RecordingsIdRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/recordings/active': {
      id: '/recordings/active'
      path: '/active'
      fullPath: '/recordings/active'
      preLoaderRoute: typeof RecordingsActiveRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/recordings/failed': {
      id: '/recordings/failed'
      path: '/failed'
      fullPath: '/recordings/failed'
      preLoaderRoute: typeof RecordingsFailedRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/recordings/processing': {
      id: '/recordings/processing'
      path: '/processing'
      fullPath: '/recordings/processing'
      preLoaderRoute: typeof RecordingsProcessingRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/verify-email/': {
      id: '/verify-email/'
      path: '/'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof VerifyEmailIndexRouteImport
      parentRoute: typeof VerifyEmailRoute
    }
    '/verify-email/success': {
      id: '/verify-email/success'
      path: '/success'
      fullPath: '/verify-email/success'
      preLoaderRoute: typeof VerifyEmailSuccessRouteImport
      parentRoute: typeof VerifyEmailRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminJobsRoute
    }
    '/admin/jobs/$id': {
      id: '/admin/jobs/$id'
      path: '/$id'
      fullPath: '/admin/jobs/$id'
      preLoaderRoute: typeof AdminJobsIdRouteImport
      parentRoute: typeof AdminJobsRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
  }
}

interface BillingRouteChildren {
  BillingCanceledRoute: typeof BillingCanceledRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  BillingIndexRoute: typeof BillingIndexRoute
}

const BillingRouteChildren: BillingRouteChildren = {
  BillingCanceledRoute: BillingCanceledRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  BillingIndexRoute: BillingIndexRoute,
}

const BillingRouteWithChildren =
  BillingRoute._addFileChildren(BillingRouteChildren)

interface ChannelsRouteChildren {
  ChannelsIdRoute: typeof ChannelsIdRoute
  ChannelsIndexRoute: typeof ChannelsIndexRoute
}

const ChannelsRouteChildren: ChannelsRouteChildren = {
  ChannelsIdRoute: ChannelsIdRoute,
  ChannelsIndexRoute: ChannelsIndexRoute,
}

const ChannelsRouteWithChildren = ChannelsRoute._addFileChildren(
  ChannelsRouteChildren,
)

interface RecordingsRouteChildren {
  RecordingsIdRoute: typeof RecordingsIdRoute
  RecordingsActiveRoute: typeof RecordingsActiveRoute
  RecordingsFailedRoute: typeof RecordingsFailedRoute
  RecordingsProcessingRoute: typeof RecordingsProcessingRoute
  RecordingsIndexRoute: typeof RecordingsIndexRoute
}

const RecordingsRouteChildren: RecordingsRouteChildren = {
  RecordingsIdRoute: RecordingsIdRoute,
  RecordingsActiveRoute: RecordingsActiveRoute,
  RecordingsFailedRoute: RecordingsFailedRoute,
  RecordingsProcessingRoute: RecordingsProcessingRoute,
  RecordingsIndexRoute: RecordingsIndexRoute,
}

const RecordingsRouteWithChildren = RecordingsRoute._addFileChildren(
  RecordingsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface VerifyEmailRouteChildren {
  VerifyEmailSuccessRoute: typeof VerifyEmailSuccessRoute
  VerifyEmailIndexRoute: typeof VerifyEmailIndexRoute
}

const VerifyEmailRouteChildren: VerifyEmailRouteChildren = {
  VerifyEmailSuccessRoute: VerifyEmailSuccessRoute,
  VerifyEmailIndexRoute: VerifyEmailIndexRoute,
}

const VerifyEmailRouteWithChildren = VerifyEmailRoute._addFileChildren(
  VerifyEmailRouteChildren,
)

interface AdminJobsRouteChildren {
  AdminJobsIdRoute: typeof AdminJobsIdRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
}

const AdminJobsRouteChildren: AdminJobsRouteChildren = {
  AdminJobsIdRoute: AdminJobsIdRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
}

const AdminJobsRouteWithChildren = AdminJobsRoute._addFileChildren(
  AdminJobsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  BillingRoute: BillingRouteWithChildren,
  ChannelsRoute: ChannelsRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OverviewRoute: OverviewRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RecordingsRoute: RecordingsRouteWithChildren,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  UsageRoute: UsageRoute,
  VerifyEmailRoute: VerifyEmailRouteWithChildren,
  AdminErrorsRoute: AdminErrorsRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminJobsRoute: AdminJobsRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminSystemRoute: AdminSystemRoute,
  AdminWorkersRoute: AdminWorkersRoute,
  AuthErrorRoute: AuthErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
